apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: frontend
        image: uraken4/devops-demo-frontend:latest
        ports:
        - containerPort: 80
      - name: backend
        image: uraken4/devops-demo-backend:latest
        ports:
        - containerPort: 5000
