# Archivo: .github/workflows/docker-build-push.yml

name: CI/CD con DevSecOps

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Detección de Secretos con GitGuardian
        uses: gitguardian/ggshield-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: Configurar Python para el backend
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias del backend
        run: pip install -r backend/requirements.txt

      - name: Análisis de Composición (SCA) y SAST con Snyk
        # Escanea dependencias y código por vulnerabilidades conocidas.
        uses: snyk/actions/python@master
        with: 
          working-directory: ./backend
          args: --scan-args="--json-file-output=snyk-python.json"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Construir y escanear imagen del frontend con Trivy
        run: |
          docker build -t uraken4/devops-demo-frontend:latest ./frontend
          docker run --rm -v $(pwd):/scan aquasec/trivy:0.43.1 --severity HIGH,CRITICAL --format table uraken4/devops-demo-frontend:latest

      - name: Construir y escanear imagen del backend con Trivy
        # Repite el mismo proceso para el backend.
        run: |
          docker build -t uraken4/devops-demo-backend:latest ./backend
          docker run --rm -v $(pwd):/scan aquasec/trivy:0.43.1 --severity HIGH,CRITICAL --format table uraken4/devops-demo-backend:latest

      - name: Log in a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push de las imágenes a Docker Hub
        run: |
          docker push uraken4/devops-demo-frontend:latest
          docker push uraken4/devops-demo-backend:latest
